version: "3.9"

services:
  backend:
    restart: unless-stopped
    volumes:
      - ./backend/:/app
    entrypoint: ./entrypoint.sh
    command: poetry run uvicorn app:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - kafka
      - zookeeper
      - akhq
      - schema-registry
    ports:
      - "8000:8000"

  db:
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "15239:5432"


volumes:
  postgresdata:
  redisdata: